classdef NImgV2
 properties
     Dmos
     DmosFlag
     Img
     ImgYcbcr
     

     %Fastfading
     ParamFastfading
     SsimFastfading
     PsnrFastfading
     MseFastfading
     CwssimFastfading
     MsssimFastfading
     IwssimFastfading
     IwpsnrFastfading    
     ColDistFastfading
     SsimFastfadingColor
     PsnrFastfadingColor
     MseFastfadingColor
     CwssimFastfadingColor
     MsssimFastfadingColor
     IwssimFastfadingColor
     IwpsnrFastfadingColor
     ColDistFastfadingColor
     SsimFastfadingInt
     PsnrFastfadingInt
     MseFastfadingInt
     CwssimFastfadingInt
     MsssimFastfadingInt
     IwssimFastfadingInt
     IwpsnrFastfadingInt
     ColDistFastfadingInt   
     ColDistFastfadingMaps

     
     ParamGblur
     SsimGblur
     PsnrGblur     
     MseGblur
     CwssimGblur
     MsssimGblur
     IwssimGblur
     IwpsnrGblur
     ColDistGblur
     SsimGblurColor
     PsnrGblurColor
     MseGblurColor
     CwssimGblurColor
     MsssimGblurColor
     IwssimGblurColor
     IwpsnrGblurColor
     ColDistGblurColor
     SsimGblurInt
     PsnrGblurInt  
     MseGblurInt
     CwssimGblurInt
     MsssimGblurInt
     IwssimGblurInt
     IwpsnrGblurInt
     ColDistGblurInt
     ColDistGblurMaps

     
     ParamJp2k
     SsimJp2k
     PsnrJp2k     
     MseJp2k
     CwssimJp2k
     MsssimJp2k
     IwssimJp2k
     IwpsnrJp2k
     ColDistJp2k
     SsimJp2kColor
     PsnrJp2kColor     
     MseJp2kColor
     CwssimJp2kColor
     MsssimJp2kColor
     IwssimJp2kColor
     IwpsnrJp2kColor
     ColDistJp2kColor
     SsimJp2kInt
     PsnrJp2kInt  
     MseJp2kInt
     CwssimJp2kInt
     MsssimJp2kInt
     IwssimJp2kInt
     IwpsnrJp2kInt
     ColDistJp2kInt
     ColDistJp2kMaps


     ParamJpeg
     SsimJpeg
     PsnrJpeg
     MseJpeg
     CwssimJpeg
     MsssimJpeg
     IwssimJpeg
     IwpsnrJpeg
     ColDistJpeg
     SsimJpegColor
     PsnrJpegColor
     MseJpegColor
     CwssimJpegColor
     MsssimJpegColor
     IwssimJpegColor
     IwpsnrJpegColor
     ColDistJpegColor
     SsimJpegInt
     PsnrJpegInt
     MseJpegInt
     CwssimJpegInt
     MsssimJpegInt
     IwssimJpegInt
     IwpsnrJpegInt
     ColDistJpegInt
     ColDistJpegMaps
     
     ParamWn
     SsimWn
     PsnrWn
     MseWn
     CwssimWn
     MsssimWn
     IwssimWn
     IwpsnrWn
     ColDistWn
     SsimWnColor
     PsnrWnColor
     MseWnColor
     CwssimWnColor
     MsssimWnColor
     IwssimWnColor
     IwpsnrWnColor
     ColDistWnColor
     SsimWnInt
     PsnrWnInt
     MseWnInt
     CwssimWnInt
     MsssimWnInt
     IwssimWnInt
     IwpsnrWnInt
     ColDistWnInt
     ColDistWnMaps
     
     ImgFastfading        
     ImgGblur       
     ImgJp2k     
     ImgJpeg          
     ImgWn
     
     ImgFastfadingCol
     ImgGblurCol
     ImgJp2kCol
     ImgJpegCol
     ImgWnCol

     ImgFastfadingInt        
     ImgGblurInt       
     ImgJp2kInt     
     ImgJpegInt          
     ImgWnInt
     
 end
end
     